### ISSUE TITLE
Canary alignment bug

### ISSUE THREAD

**Issue by futherus** [d3phys/Stack#5]
Dump of memory at address `stk.items` shows unused 16 bytes of memory between actual data and right `items`'s canary. This memory is unprotected, verificator doesn't state anything about it.

(Canaries highlighted with yellow, actual data with green, 8 bytes of unused and unprotected memory with red)

![изображение](https://user-images.githubusercontent.com/89441309/137815658-0180f3ae-5481-4868-bcf7-64a649afafe3.png)

![изображение](https://user-images.githubusercontent.com/89441309/137815770-b62316d6-3bb3-4b51-82eb-d21caca87a70.png)

![изображение](https://user-images.githubusercontent.com/89441309/137815880-37e18bd0-7ba5-4fe6-a0db-2934cb399863.png)

Stack dump does not state anything about invasion:

![изображение](https://user-images.githubusercontent.com/89441309/137816117-3bf72030-2bcf-43ff-ba5e-5df40b679ddf.png)

main.cpp substitution to examine described bug.

[main.cpp.canary_alignment_bug.txt](https://github.com/d3phys/Stack/files/7368905/main.cpp.canary_alignment_bug.txt)

**Comment by d3phys** [comment]
That is an expected behaviour. Hash and canaries protect _independently_... These bytes are canaries alignment.
Thank you!
